import csv
import json
import datetime
from pathlib import Path

from core.logger import get_logger
from core.models import Report

logger = get_logger("output.writer")


SENSITIVE_PATHS: list[str] = [
    "/.git/config", "/.env", "/phpinfo.php", "/info.php",
    "/wp-config.php.bak", "/config.json",
    "/backup.sql", "/dump.sql",
    "/robots.txt", "/sitemap.xml",
    "/crossdomain.xml", "/client-access-policy.xml",
    "/.htaccess", "/.htpasswd",
    "/swagger.json", "/api-docs",
    "/.aws/credentials", "/.azure/credentials",
    "/.npmrc", "/.pypirc",
    "/health", "/metrics", "/actuator", "/actuator/env",
    "/debug", "/console", "/server-status",
]


def write_csv(report: Report, output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "report.csv"
    with path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["Vulnerability", "URL", "Payload", "Impact"])
        for finding in report.findings:
            writer.writerow([
                finding.finding_type.value.upper(),
                finding.url,
                finding.payload or "",
                f"{finding.severity.value} - {finding.detail}",
            ])
        for secret in report.secrets:
            writer.writerow([
                "SECRET_" + secret.secret_type.value.upper(),
                secret.url,
                secret.match[:120],
                secret.severity.value,
            ])
    logger.info("wrote CSV report: %s (%d bytes)", path, path.stat().st_size)
    return path


def write_json(report: Report, output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "report.json"
    data = {
        "target": report.target,
        "timestamp": report.timestamp,
        "findings": [
            {
                "type": f.finding_type.value,
                "url": f.url,
                "parameter": f.parameter,
                "payload": f.payload,
                "confidence": f.confidence,
                "severity": f.severity.value,
                "detail": f.detail,
            }
            for f in report.findings
        ],
        "secrets": [
            {
                "url": s.url,
                "secret_type": s.secret_type.value,
                "match": s.match[:120],
                "severity": s.severity.value,
                "detail": s.detail,
            }
            for s in report.secrets
        ],
        "ai_summary": report.ai_summary,
    }
    with path.open("w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
    logger.info("wrote JSON report: %s (%d bytes)", path, path.stat().st_size)
    return path


def write_md(report: Report, output_dir: Path) -> Path:
    output_dir.mkdir(parents=True, exist_ok=True)
    path = output_dir / "report.md"
    lines = [
        f"# Bug Bounty Report — {report.target}",
        f"**Generated**: {report.timestamp}",
        "",
        "## Findings",
    ]
    if report.findings:
        for f in report.findings:
            lines.append(f"- **[{f.severity.value.upper()}][{f.finding_type.value}]** {f.url}")
            if f.parameter:
                lines.append(f"  - Parameter: `{f.parameter}`")
            if f.payload:
                lines.append(f"  - Payload: `{f.payload}`")
            lines.append(f"  - {f.detail}")
    else:
        lines.append("*No findings*")

    if report.secrets:
        lines.extend(["", "## Secrets Found"])
        for s in report.secrets:
            lines.append(f"- **[{s.severity.value.upper()}]** {s.url}")
            lines.append(f"  - Type: {s.secret_type.value}")
            lines.append(f"  - Match: `{s.match[:100]}`")

    if report.ai_summary:
        lines.extend(["", "## AI Analysis Summary", report.ai_summary])

    lines.extend(["", "---", "*Report generated by Bug Bounty Framework*"])
    with path.open("w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    logger.info("wrote MD report: %s (%d bytes)", path, path.stat().st_size)
    return path


def write_all(report: Report, output_dir: Path) -> dict[str, Path]:
    return {
        "json": write_json(report, output_dir),
        "csv": write_csv(report, output_dir),
        "md": write_md(report, output_dir),
    }
